<a href="https://colab.research.google.com/github/shmoralesh/hyperblog/blob/main/Clase_Muestreo_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import random
import io

### Leemos la base de datos a trabajar en nuestra ruta de origen

In [ ]:
### Esta secuencia nos permite seleccionar el archivo a subir al colab. Toca disminuir la seguridad para el sitio
from google.colab import files
uploaded = files.upload()

Saving economia-y-turismo-en-el-centro-historico.csv to economia-y-turismo-en-el-centro-historico.csv

In [ ]:
### Importamos como tal la tabla con read_CSV
econdata = pd.read_csv(io.BytesIO(uploaded["economia-y-turismo-en-el-centro-historico.csv"]))

In [ ]:
econdata.head()

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
0,0,"19.424781053,-99.1327537959","{""type"": ""Polygon"", ""coordinates"": [[[-99.1332...",307_130_11,Cuauhtémoc,B,Mercado,Pino Suárez
1,1,"19.4346139576,-99.1413808393","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_008_01,Cuautémoc,A,Museo,Museo Nacional de Arquitectura Palacio de Bell...
2,2,"19.4340695945,-99.1306348409","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",006_002_12,Cuautémoc,A,Museo,Santa Teresa
3,3,"19.42489472,-99.12073393","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_102_06,Venustiano Carranza,B,Hotel,Balbuena
4,4,"19.42358238,-99.12451093","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_115_12,Venustiano Carranza,B,Hotel,real

### Funciones de muestreo:

#### 1) Muestreo aleatorio simple:

In [ ]:
# Vamos a hacer una muestra de ocho registros
aleat_8 = econdata.sample(n=8)
aleat_8

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
99,99,"19.4438918423,-99.1402516182","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",003_052_18,Cuautémoc,B,Hotel,Drigales
150,150,"19.440448428,-99.1365429261","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_065_10,Cuautémoc,B,Hotel,Moderno
111,111,"19.4430614318,-99.1353793874","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_107_02,Cuautémoc,B,Hotel,Embajadores
94,94,"19.4338001466,-99.1463273233","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_016_02,Cuautémoc,B,Museo,Arte Popular
24,24,"19.4285279152,-99.147008562","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_067_19,Cuautémoc,B,Hotel,Fornos
73,73,"19.4218384283,-99.1267852296","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",007_005_07,Cuautémoc,B,Hotel,Jaen
170,170,"19.43162145,-99.13535842","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",001_028_11,Cuautémoc,A,Hotel,NH Hoteles
169,169,"19.4365391003,-99.1335799561","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_093_16,Cuautémoc,A,Hotel,Azores

In [ ]:
### Lo hacemos de nuevo para verificar que si es aleatorio
aleat_8_2 = econdata.sample(n=8)
aleat_8_2

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
154,154,"19.4245820084,-99.1259208824","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",307_119_06,Cuautémoc,B,Hotel,Las Vegas
66,66,"19.4331350004,-99.1382989213","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",001_021_14,Cuautémoc,A,Hotel,Coliseo
140,140,"19.4374331486,-99.1457705763","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",003_092_06,Cuautémoc,A,Hotel,Boutique Cortes
146,146,"19.4373584031,-99.1383047535","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_090_14,Cuautémoc,A,Hotel,Congreso Garage
22,22,"19.4348361174,-99.1467786287","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_015_01,Cuautémoc,B,Hotel,Fiesta Inn
72,72,"19.4454901265,-99.1471012862","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",003_046_14,Cuautémoc,B,Hotel,Atoyac
107,107,"19.4248237343,-99.1311696681","{""type"": ""Polygon"", ""coordinates"": [[[-99.1313...",307_128_04,Cuauhtémoc,B,Mercado,San Lucas
126,126,"19.42774805,-99.12796532","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",006_078_04,Cuautémoc,A,Hotel,San Marcos

In [ ]:
### Elegimos el 25% de nuestros datos
prop_25 = econdata.sample(frac=.25)
prop_25.head()

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
49,49,"19.4264953358,-99.1248854383","{""type"": ""Polygon"", ""coordinates"": [[[-99.1252...",323_139_01,Venustiano Carranza,B,Mercado,Dulceria Don Goloso
29,29,"19.4291936373,-99.1244027626","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_145_10,Venustiano Carranza,B,Hotel,Tampico
150,150,"19.440448428,-99.1365429261","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_065_10,Cuautémoc,B,Hotel,Moderno
167,167,"19.4387807061,-99.1398360896","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_072_07,Cuautémoc,A,Hotel,"Diligencias, S.A."
165,165,"19.4248396624,-99.1333096809","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",001_086_01,Cuautémoc,B,Hotel,Latino

#### Muestreo sistemático: Tiene una norma, o intervalo regular

In [ ]:
# Se define una función usando econdata
def systematic_sampling(econdata,step):
  # Se definen los índices que van desde el cero hasta la longitud de econdata, para integrar los posibles valores
  # El step, o la función de intervalos la definiremos a continuación
  # Los indexes modifican: donde empieza la selección, donde termina, y de cuanto es cada salto
  indexes = np.arange(0,len(econdata),step=step)
  systematic_sample = econdata.iloc[indexes]
  # y se devuelve el valor de systematic sample
  return systematic_sample

# Llamamos la función y le decimos que seleccione datos de 3 en 3
systematic_sample = systematic_sampling(econdata,3)
systematic_sample

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
0,0,"19.424781053,-99.1327537959","{""type"": ""Polygon"", ""coordinates"": [[[-99.1332...",307_130_11,Cuauhtémoc,B,Mercado,Pino Suárez
3,3,"19.42489472,-99.12073393","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_102_06,Venustiano Carranza,B,Hotel,Balbuena
6,6,"19.43553422,-99.12324801","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",318_116_11,Venustiano Carranza,B,Hotel,San Antonio Tomatlan
9,9,"19.4407152937,-99.1498060057","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",012_146_22,Cuautémoc,B,Hotel,Detroit
12,12,"19.43990186,-99.14813347","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",003_079_16,Cuautémoc,B,Hotel,La Paz
...,...,...,...,...,...,...,...,...
216,216,"19.4247697438,-99.1249707246","{""type"": ""Polygon"", ""coordinates"": [[[-99.1250...",323_118_37,Venustiano Carranza,B,Mercado,Lamininas de La Merced
219,219,"19.4234096295,-99.1438351156","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_118_03,Cuautémoc,B,Hotel,Prado Floresta
222,222,"19.4397905042,-99.134628735","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_063_10,Cuautémoc,A,Hotel,Ladero
225,225,"19.43094655,-99.12455418","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_027_04,Venustiano Carranza,B,Hotel,Gran Veracruz
228,228,"19.4406567734,-99.1394531646","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_069_01,Cuautémoc,B,Museo,Tequila y Mescal

#### 3) Muestreo estratificado

In [ ]:
# Creamos la variable de estratificación

# Creamos una columna juntando el lugar y el sitio y después contamos cuantos datos están en cada uno. Lo dividimos entrela cantidad de datos de la BD (len(econdata))
# Se organizan en orden descendente (sort_values(ascending=False))
econdata["estratificado"] = econdata["delegacion"] + "," + econdata["tipo"]
(econdata["estratificado"].value_counts()/len(econdata)).sort_values(ascending=False)

Cuautémoc,Hotel                0.643478
Cuautémoc,Museo                0.156522
Venustiano Carranza,Hotel      0.078261
Cuauhtémoc,Mercado             0.073913
Venustiano Carranza,Mercado    0.047826
Name: estratificado, dtype: float64

Nuestros datos dicen que la proporción es la siguiente:

1) hoteles en Cuauhtemoc 0.5

2) Museos en Cuauhtémoc 0.2

3) Hoteles en VEnustiano Carranza 0.1

4) Mercados en Cuauhtémoc 0.1

5) Mercados en Venistiano Carranza 0.1

In [ ]:
# Crear una nueva función con: econdata, los nombres de las columnas estratificadas, los valores estratificados, las proporciones estratificadas, y el random state = None
def data_estratificada(econdata,nombres_columnas_estrat,valores_estrat,prop_estrat,random_state=None):
  # Vamos a crear un data frame vacío con los nombre de columnas son las columnas de econdata
  df_estrat = pd.DataFrame(columns = econdata.columns)

  # Nuestra posición inicia en -1
  pos = -1
  # Creamos un ciclo for que va desde i hasta la longitud de los valores estratificados
  for i in range(len(valores_estrat)):
    # Le vamos sumando 1 a cada posición
    pos += 1
    # Y si la posición llega a ser igual a la logitud de los valores estratificados menos 1 valor
    if pos == len(valores_estrat) - 1:
      # a continuación definiremos la ratio de la longitud, que será la resta de la longitud de econdata menos la longitud de la nueva dataframe
      # la idea es que se esté comparando todo el tiempo
      ratio_len = len(econdata)- len(df_estrat)
    else:
      # De lo contrario definimos un nuevo ratio, y le diremos que es un entero de la longitud de econdata y lo equivale  la proporción estratificada que vamos a definir, para cada uno de los i
      # Esto nos ayuda a calcular cual es cada una de las filas, el componente i, y a sacar el ratio en basa a cada una de la proporción seleccionada
      ratio_len = int(len(econdata) * prop_estrat[i])

    # Luego creamos el data frame filtrado, a partir de la tabla de econdata, extrayendo los nombres de las columnas estratificadas y dándole los valores para cada elemento i
    df_filtrado = econdata[econdata[nombres_columnas_estrat] == valores_estrat[i]]
    df_temp = df_filtrado.sample(replace=True, n=ratio_len, random_state=random_state)

    # Se modifica el data frame vacio pegandole los valores
    df_estrat = pd.concat([df_estrat, df_temp])

  # Se devuelve el valor de la variable modificada
  return df_estrat

In [ ]:
# Se inicializan los valores necesarios para correr la función
valores_estrat = ["Cuautémoc,Hotel","Cuautémoc,Museo","Venustiano Carranza,Hotel","Cuauhtémoc,Mercado","Venustiano Carranza,Mercado"]
# Se colocan las proporciones que habíamos definido
prop_estrat = [0.5,0.2,0.1,0.1,0.1]

# Iniciamos la función con los datos que habíamos definido
df_estrat = data_estratificada(econdata,"estratificado",valores_estrat,prop_estrat,random_state=42)
df_estrat

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id,estratificado
164,164,"19.4388741511,-99.1413308257","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",003_113_03,Cuautémoc,B,Hotel,Dos Naciones,"Cuautémoc,Hotel"
142,142,"19.4263681354,-99.1327278126","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",006_127_14,Cuautémoc,A,Hotel,Ambar,"Cuautémoc,Hotel"
27,27,"19.4348360773,-99.1463945583","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_016_01,Cuautémoc,B,Hotel,Hilton Centro Histórico,"Cuautémoc,Hotel"
168,168,"19.4349726565,-99.147766133","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_014_23,Cuautémoc,B,Hotel,One Alameda,"Cuautémoc,Hotel"
113,113,"19.43374405,-99.13550135","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",001_012_13,Cuautémoc,A,Hotel,San Antonio,"Cuautémoc,Hotel"
...,...,...,...,...,...,...,...,...,...
128,128,"19.4270781084,-99.1210175514","{""type"": ""Polygon"", ""coordinates"": [[[-99.1214...",323_061_04(123),Venustiano Carranza,B,Mercado,San Ciprian,"Venustiano Carranza,Mercado"
37,37,"19.4271233834,-99.125111772","{""type"": ""Polygon"", ""coordinates"": [[[-99.1251...",323_065_01,Venustiano Carranza,B,Mercado,Dulceria,"Venustiano Carranza,Mercado"
163,163,"19.4265454033,-99.1224859032","{""type"": ""Polygon"", ""coordinates"": [[[-99.1231...",323_063_05,Venustiano Carranza,B,Mercado,NaN,"Venustiano Carranza,Mercado"
156,156,"19.4255480371,-99.1249308096","{""type"": ""Polygon"", ""coordinates"": [[[-99.1253...",323_138_04 (3),Venustiano Carranza,B,Mercado,Mariscos,"Venustiano Carranza,Mercado"
37,37,"19.4271233834,-99.125111772","{""type"": ""Polygon"", ""coordinates"": [[[-99.1251...",323_065_01,Venustiano Carranza,B,Mercado,Dulceria,"Venustiano Carranza,Mercado"